# Generated by Django 4.0.4 on 2022-06-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_words'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='words',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='words',
            old_name='activate',
            new_name='activated',
        ),
    ]
