# Generated by Django 4.0.4 on 2022-07-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='response',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
