# Generated by Django 4.0.4 on 2022-07-05 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0008_invitation_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.CharField(max_length=8)),
                ('Failures', models.CharField(max_length=5)),
                ('activated', models.BooleanField(blank=True, default=False)),
                ('game_over', models.BooleanField(blank=True, default=False)),
                ('winner', models.BooleanField(blank=True, default=False)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_guest_user', to=settings.AUTH_USER_MODEL)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_host_user', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_words', to='hangman.words')),
            ],
        ),
    ]
