# Generated by Django 4.0.4 on 2022-07-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0009_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Failures',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='hits',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
