# Generated by Django 4.0.4 on 2022-07-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0010_alter_room_failures_alter_room_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='word_id',
            field=models.IntegerField(default=0),
        ),
    ]
