# Generated by Django 4.0.4 on 2022-07-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0011_invitation_word_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='word_id',
            field=models.IntegerField(default=1),
        ),
    ]
