# Generated by Django 4.0.4 on 2022-07-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0012_alter_invitation_word_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Failures',
            new_name='failures',
        ),
    ]
