# Generated by Django 4.0.4 on 2022-07-10 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0014_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
