# Generated by Django 4.0.4 on 2022-07-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0015_profile_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='failures',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
